lqr_node:
    ros__parameters:
        # SETTINGS
        is_debug_mode: true
        is_first_lap:  false
        is_constant_speed: true
        target_speed: 0.2
        # SUPPORT FILES
        trajectory_filename: "/varano_x_y_r_v.csv"
        odom_topic: "/simulation_state"
        control_topic: "/car_controls"
        debug_odom_topic: "/debug/odometry"
        partial_traj_topic: "/planning/centerline"
        # CAR PHYSICAL PARAMETERS
        car_mass: 270.0
        front_length: 1.10
        rear_length: 0.60
        C_alpha_front: 10000.0
        C_alpha_rear: 10000.0
        # PID parameters
        PID_p:  1.0
        PID_i:  0.0
        PID_d:  0.0
        # CONTROL VECTORS 
        vectors_k:
          - "5.0 -1.0000 -0.2000 0.5000 0.0101"
          - "10.0 -1.0000 -0.2000 0.5000 0.0101"
          - "15.0 -1.0000 -0.2000 0.5000 0.0101"
          - "20.0 -1.0000 -0.2000 0.5000 0.0101"