lqr_node:
    ros__parameters:
        is_debug_mode: true
        is_first_lap:  false
        is_constant_speed: false
        target_speed: 5.0
        trajectory_filename: "/vallelunga_x_y_r_v.csv"
        odom_topic: "/odometry"
        control_topic: "/control"
        debug_odom_topic: "/debug/odometry"
        partial_traj_topic: "/planning/centerline"
        dummy_proportionality_constant: 10.0
        car_mass: 270.0
        front_length: 1.10
        rear_length: 0.60
        C_alpha_front: 10000.0
        C_alpha_rear: 10000.0
        vectors_k:
          - "5.0 -0.5381 -0.0456 4.0650 0.3252"
          - "10.0 -0.4542 -0.0648 4.6136 0.4894"
          - "15.0 -0.4144 -0.0797 5.0552 0.5823"
          - "20.0 -0.3920 -0.0916 5.3822 0.6425"