lqr_node:
    ros__parameters:
        is_debug_mode: true
        is_first_lap:  false
        is_constant_speed: false
        target_speed: 5.0
        trajectory_filename: "/vallelunga_x_y_r_v.csv"
        odom_topic: "/odometry"
        control_topic: "/control"
        debug_odom_topic: "/debug/odometry"
        partial_traj_topic: "/planning/centerline"
        dummy_proportionality_constant: 10.0
        car_mass: 270.0
        front_length: 1.10
        rear_length: 0.60
        C_alpha_front: 10000.0
        C_alpha_rear: 10000.0
        vectors_k:
          - "1.0 2.0 3.0 4.0 5.0"
          - "6.0 7.0 8.0 9.0 10.0"
          - "11.0 12.0 13.0 14.0 15.0"